### ISSUE TITLE
Some tests swap the parameters for expected and actual result

### ISSUE THREAD

**Issue by DBX12** [dnnrly/hoofli#16]
**Describe the bug**
Some tests swap expected and actual result which leads to confusing outputs in case of failing tests. At time of writing, this affects these test methods:

- TestDrawHar_SinglePage in [har_test.go:72](https://github.com/dnnrly/hoofli/blob/958ad940816324274e3a4f5c1f348be8b236fcca/har_test.go#L72)
- TestDrawHar_MultiPage in [har_test.go:117](https://github.com/dnnrly/hoofli/blob/958ad940816324274e3a4f5c1f348be8b236fcca/har_test.go#L117)
- TestDrawHar_InitiatorTypes in [har_test.go](https://github.com/dnnrly/hoofli/blob/958ad940816324274e3a4f5c1f348be8b236fcca/har_test.go#L172)

**To Reproduce**
1. Break a test by replacing the contents of `test/reference/plantuml/simple-example.puml` with _this is not puml code_
2. Run tests
3. See test failure report for `TestDrawHar_SinglePage` reading:
    ```
    Not equal:
    expected: "@startuml ....."
    actual: "this is not puml\n"
    ```

**Expected behavior**
Test failure report should read
 ```
Not equal:
expected: "this is not puml\n"
actual: "@startuml ....."
 ```

**Comment by DBX12** [comment]
I can work on that, but fear we might get merge conflicts so I filed an issue first.

**Comment by dnnrly** [comment]
No, you go ahead and fix it. Anything that comes in, I'll make sure works around it!
